version: '3.0'

services:
    application:
        build: ./containers/apache/${APACHE_VERSION}/php/${PHP_VERSION}
        hostname: application
        environment:
            - LOG_LEVEL=${APPLICATION_LOG_LEVEL}
        volumes:
            - ./src${APPLICATION_FOLDER}:/var/www/html
            - ./logs/php:/var/log/php
            - ./logs/app:/var/log/app
        restart: always

    server:
        build: ./containers/nginx/${NGINX_VERSION}
        hostname: server
        ports:
            - 80:80
        volumes:
            - ./src${APPLICATION_FOLDER}:/var/www/html
            - ./logs/nginx/:/var/log/nginx
        command: nginx -g 'daemon off;'
        restart: always

    mysql:
        build: ./containers/mariadb/${MARIADB_VERSION}
        hostname: database
        environment:
            MYSQL_DATABASE: ${DATABASE_NAME}
            MYSQL_USER: ${DATABASE_USER}
            MYSQL_PASSWORD: ${DATABASE_PASSWORD}
            MYSQL_ROOT_PASSWORD: ${DATABASE_ROOT_PASSWORD}
        ports:
            - 3306:3306
        volumes:
            - ./database/mysql:/var/lib/mysql
            - ./database/backup:/backup
            - ./logs/mysql:/var/log/mysql
        restart: always

    database-management-system:
        image: adminer
        hostname: database-management-system
        environment:
            ADMINER_DEFAULT_SERVER: db
        ports:
            - 5000:8080
        restart: always

    mail:
        image: mailhog/mailhog
        command: ["-smtp-bind-addr", "0.0.0.0:25"]
        user: root
        expose:
            - 25
            - 8025
        ports:
            - 8025:8025

